markdown: kramdown
permalink: /post/:title/

paginate: 5
paginate_path: '/blog/:num/'

name: Arthur Gouveia
url: http://arthurgouveia.com
description: A wild blog appears.
image: facebook.png
twitter: ArthurGouveia
github: ArthurGouveia
codepen: ArthurGouveia
instagram: ArthurGouveia
gravatar_url: https://s.gravatar.com/avatar/1bbd6316097511709d3b9c7a6f6cca41
google_analytics_tracking_id: UA-8502733-1
